on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: false
        default: '24.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      
      - name: Build and Format
        run: |
          sh build.sh
          sh format.sh
        env:
          is_os_darwin_mac: 0
          is_os_window: 0
          is_os_wsl: 0
          is_os_ubuntu: 1
          is_os_chromeos: 0
          is_os_mingw64: 0
          is_os_android_termux: 0
